name: 'Build'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build

  notify-slack-success:
    runs-on: ubuntu-latest
    needs: [build]
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: seatsio/seatsio-github-actions/slack-notify-clientlib-build-success@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  notify-slack-failure:
    runs-on: ubuntu-latest
    needs: [build]
    if: failure() && github.ref == 'refs/heads/main'
    steps:
      - uses: seatsio/seatsio-github-actions/slack-notify-build-failure@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
